name: Docker Image CI

on:
  push:
    #branches: [main]
    branches:
      - main
      - stable
    tags:
      - 'v?[0-9]+.[0-9]+.[0-9]+

  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # - name: Build the Docker image
      #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      - name: Install Packages
        run: npm install
        
      - name: Run tests
        run: npm run test

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      #- name: Extract metadata (tags, labels) for Docker
       # id: meta
        #uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        #with:
         # images: lexferramirez/dashpira
         
      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v3.6.0
        with:
          images: lexferramirez/dashpira
          tags: |
            event=branch,type=raw,value={{branch}}-{{sha}}  # <---- triggered on push a tag
            event=branch,type=ref,suffix=-{{sha}}
            event=tag,type=semver,pattern={{version}}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  # publish:

  #   needs: build
